baseURL = "/"
languageCode = "en-us"
title = "Rare Book Libraries Data"

themesDir = "themes"
theme = "hugo-whisper-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Docs"
    url = "/docs/"
    weight = 2

[params]
  google_analytics_id=""
  homepage_button_link = '/docs'
  homepage_button_text = 'Read The Docs'
  homepage_intro = 'This site provides access to the collections data from numerous special collections at American liberal arts colleges.'
  homepage_image = '/images/lvivcardcatalog.jpg'

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "Data about special collections in liberal arts colleges."
    meta_og_title = "Rare Book Libraries Data"
    meta_og_type = "website"
    meta_og_url = "https://www.rarebooklibrarian.com/"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-whisper-theme/master/images/tn.png"
    meta_og_description = "Data about special collections in liberal arts colleges."
    meta_twitter_card = "summary"
    meta_twitter_site = "@mark_e_peterson"
    meta_twitter_creator = "@mark_e_peterson"

  [params.logo]
      mobile = "/images/logo-mobile.svg"
      standard  = "/images/logo.svg"
